#1
oc_platform_home:
    path:    /{page}
    defaults: {_controller: OCPlatformBundle:Advert:index, page:1 }
    requirements:
        page: \d*
#2
oc_platform_view:
    path:    /advert/{id}
    defaults: {_controller: OCPlatformBundle:Advert:view }
    requirements:
        id: \d+
#3
oc_platform_add:
    path:    /add
    defaults: {_controller: OCPlatformBundle:Advert:add }
#4
oc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id: \d+
#5
oc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+